/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedsIndexRouteImport } from './routes/feeds/index'
import { Route as FeedsIdRouteImport } from './routes/feeds/$id'
import { Route as EntriesIdRouteImport } from './routes/entries/$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIdRoute = FeedsIdRouteImport.update({
  id: '/feeds/$id',
  path: '/feeds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRoute
  '/entries/$id': typeof EntriesIdRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRoute
  '/entries/$id': typeof EntriesIdRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRoute
  '/entries/$id': typeof EntriesIdRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user' | '/entries/$id' | '/feeds/$id' | '/feeds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user' | '/entries/$id' | '/feeds/$id' | '/feeds'
  id: '__root__' | '/' | '/user' | '/entries/$id' | '/feeds/$id' | '/feeds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRoute
  EntriesIdRoute: typeof EntriesIdRoute
  FeedsIdRoute: typeof FeedsIdRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$id': {
      id: '/feeds/$id'
      path: '/feeds/$id'
      fullPath: '/feeds/$id'
      preLoaderRoute: typeof FeedsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRoute,
  EntriesIdRoute: EntriesIdRoute,
  FeedsIdRoute: FeedsIdRoute,
  FeedsIndexRoute: FeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
